#! /bin/sh

#setxkbmap semimak -variant angle -option caps:escape -option compose:menu
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#feh --bg-fill images/mountain-night.png
xsetroot -cursor_name left_ptr
xautolock -time 3 -locker slock &
pgrep -x pipewire > /dev/null
pipewire &
pgrep -x pipewire-pulse > /dev/null
pipewire-pulse &
polybar main &
picom --experimental-backends & 
emacs --daemon &
